### ISSUE TITLE
[Bug]: SDVDN did not working.

### ISSUE THREAD

**Issue by AryanGoAnimateCool** [scripthookvdotnet/scripthookvdotnet#1401]
### What modules are you seeing the problem on?

ScriptHookVDotNet.asi (runtime)

### SHVDN Version

b226622

### Game Version

v1.0.3095

### Bug Description

when I launching GTA 5, I get this error
![image_2024-02-09_163619961](https://github.com/scripthookvdotnet/scripthookvdotnet/assets/101686823/c04a564b-99ea-4199-a74c-3e47899d8439)
Any fixes?

### Steps To Reproduce

1. start the game.
2. get this error

### Link To Code Example

none

### The Current Behavior

ScriptHookV will gives this error
CORE: An exception occurred while executing *ScriptHookVDotNet.asi' (0x00007FFFE93C25B0), id 37

### The Expected Behavior

ScriptHookV executing ScriptHookVDotNet

**Comment by kagikn** [comment]
Not sufficient info to reproduce the issue. There must be more conditions to reproduce the issue other than just starting the game .

**Comment by aryanmaulana7636** [comment]
I used mods
Simple Trainer
Menyoo 2.0.0 (Unofficial by ItsJustCurtis)
Natural Vision Evolved.
ScriptHookV
ScriptHookVDotNet
Sell Cars Mod
Lemon UI
MK2 Ammo Giver
And More.

**Comment by kagikn** [comment]
Just listing all the mods you installed doesn't help too much to identify what is responsible to the issue. Try disable some of the mods other than SHVDN and its dependencies and find a way to reproduce the issue.

**Comment by aryanmaulana7636** [comment]
turns out, it's was GTA V Upscaler that's causing problem, so I disabled GTA V Upscaler, and error is fixed.

**Comment by kagikn** [comment]
Well, although the bug report fails to describe how the issue behaves enough, it turns out SHVDN was responsible for this issue. A Stranger, who is the supreme moderator, told me that she had also experienced the same error and it happened **RANDOMLY**. If she didn't say it happened randomly, I might have not thought of where the bug is at.

**Comment by kagikn** [comment]
Reopening as a new similar issue was created, which I think the same bug causes as this issue. Most multithreading bugs are non-deterministic since they involves data races or race conditions and I haven't reproduce this issue once, so don't think I could spot what is wrong with this issue within an hour...

**Comment by cpt-levi23** [comment]
So, upon using your shvdn v3.6.0 it still crashes upon start up.
![Screenshot 2024-02-19 140759](https://github.com/scripthookvdotnet/scripthookvdotnet/assets/112290295/eee34799-ba7f-4997-8540-97e08e27aa3a)

**Comment by Hydraxonn** [comment]
I'd like to throw my hat in the ring here. I'm also getting this non-deterministic crash with SHVDN. I've found that people using ReShade find this crash more commonly. I have a large (~50GB) mods folder and almost 100 scripts, but even when I remove all but one script the crash can still happen. I fully understand how frustrating it can be to troubleshoot a random issue that's this hard to reproduce, so I'd be happy to help test, report or otherwise help to get to the bottom of this issue. It all comes back around to #976 Please let me know if there are any logs I can provide or special versions I can use with extended logging to help identify issues. Thanks so much @kagikn for your incredible work keeping this vital tool alive!

**Comment by kagikn** [comment]
I believe this issue is already resolved as how #1454 got resolved.
